### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [maybenextime/ReversiGame#1]
1. Алгоритм бота получился какой-то примитивный (даже для уровня `hard`). Попробуйте реализовать минимакс с настраиваемой глубиной (см. лекции и примеры). Сложность можно регулировать глубиной перебора (а текущие Nornal и Hard убрать)

Дальше замечания по стилю

2. За год изучания Джавы уже можно было бы научиться соблюдать принятый стиль кодирования. Классы принято называть с большой буквы.
3. https://github.com/maybenextime/ReversiGame/blob/a3a7e841e5418c50a10fa57228fa102688bc2922/src/botHard.java#L1

Этот импорт лишний

4. https://github.com/maybenextime/ReversiGame/blob/a3a7e841e5418c50a10fa57228fa102688bc2922/src/botHard.java#L8-L17

В таких местах лучше добавить `static` и `final` (не только здесь)

5. `char` - не самое лучшее представление для ячейки. Сделайте перечисление или класс для элементов поля (шашка, ячейка).

6. https://github.com/maybenextime/ReversiGame/blob/a3a7e841e5418c50a10fa57228fa102688bc2922/src/gamePlay.java#L66-L177

Попробуйте обобщить эти обходы, сейчас выглядит как куча повторяющегося кода.

7. Постарайтесь  сделать поля у классов `private` и сделать нужные методы для изменения состояния. То, что вы меняете поля напрямую, сильно запутывает код.

**Comment by tdw97** [comment]
Я исправил.  Можно посмотреть мою работу. Пока мая работа достигает оценка 4?

**Comment by gagarski** [comment]
А почему в `Minimax` вы не используете `Board`, а используете массив? Попробуйте отделить представление доски от её модели и использовать её везде, где можно.

Да, достигает 4, даже чуть больше.

**Comment by tdw97** [comment]
Board это JPanel только для рисовании и установки JButton( back, next, reset) .А GamePlay это правило и состояние игры ( board, current color). Поэтому ,я думаю , Что не нужно использовать Board  в Minimax
